version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: guzzlehttp/psr7
    versions:
    - 1.7.0
    - 1.8.1
