language: php

sudo: false

env:
  global:
    - TEST="./vendor/bin/phpunit"

matrix:
  include:
    - php: 7.1
      env: CS=true
    - php: 7.1
      env: PHPUNIT=true
    - php: 7.1
      env: PHPSTAN=true
    - php: 7.2
      env: PHPUNIT=true SEND_COVERAGE=true PHP_VERSION=7.2
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - composer validate

before_script:
  - chmod a+x ./build/travis/script.sh && chmod a+x ./build/travis/after_success.sh

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-progress --profile --no-suggest
  - if [[ "$PHP_VERSION" = 7.2 ]]; then composer req --dev viserio/http; fi

script:
  - ./build/travis/script.sh

after_success:
  - ./build/travis/after_success.sh

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5886ad33ac123a7c06b0
