dist: trusty
language: php

env:
  global:
    - TEST="./vendor/bin/phpunit --verbose"
    - COMPOSER_UP="composer update --no-interaction --prefer-dist --no-progress --profile --no-suggest"

cache:
  yarn: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer

before_install:
  - stty cols 120
  - chmod a+x ./build/travis/configure_php.sh
  - ./build/travis/configure_php.sh

install:
  - composer global require hirak/prestissimo
  - $COMPOSER_UP

jobs:
  include:
    - stage: Test
      php: 7.1
      env: REMOVE_XDEBUG=true
    - stage: Test
      php: 7.2
      env: REMOVE_XDEBUG=true
      install:
        - composer global require hirak/prestissimo
        - $COMPOSER_UP
        - composer require viserio/http:dev-master

    - stage: Coding standard
      php: 7.2
      env: REMOVE_XDEBUG=true
      script:
        - ./vendor/bin/php-cs-fixer fix --verbose --diff --dry-run
    - stage: Coding standard
      php: 7.2
      env: REMOVE_XDEBUG=false
      script:
        - ./vendor/bin/phpstan analyse -c phpstan.neon -l 7 src

    - stage: Coverage
      php: 7.2
      env: REMOVE_XDEBUG=false
      script:
        - bash -xc "$TEST -c ./phpunit.xml.dist --coverage-clover=coverage.xml"
      after_success:
        - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    on_success: never
    on_failure: change